export const projects = [
  {
    name: 'Weather Dashboard',
    description: 'Probably the most random thing you have ever seen!',
    technologies: '',
    liveLink: '',
    githubLink: '',
  },
  {
    name: 'Math Magicians',
    description: 'Probably the most random thing you have ever seen!',
    technologies: '',
    liveLink: '',
    githubLink: '',
  },
  {
    name: 'Free-to-Play Games',
    description: 'Probably the most random thing you have ever seen!',
    technologies: '',
    liveLink: '',
    githubLink: '',
  },
  {
    name: "Space Traveler's Hub",
    description: 'Probably the most random thing you have ever seen!',
    technologies: '',
    liveLink: '',
    githubLink: '',
  },
  {
    name: "Virag's Web Development Course",
    description: 'Probably the most random thing you have ever seen!',
    technologies: '',
    liveLink: '',
    githubLink: '',
  },
  {
    name: 'Bookstore',
    description: 'Probably the most random thing you have ever seen!',
    technologies: '',
    liveLink: '',
    githubLink: '',
  },
  {
    name: 'Catalog of My Things',
    description: 'Probably the most random thing you have ever seen!',
    technologies: '',
    liveLink: '',
    githubLink: '',
  },
];
