export const styles = {
  width: '70vw',
  maxWidth: '1500px',
  '@media (max-width: 1200px)': {
    width: '95vw',
    maxHeight: 'unset',
    margin: '80px 0 50px 0',
  },
  height: '85vh',
  maxHeight: '1000px',
  background: 'rgba(0, 0, 28, 0.8)',
  backdropFilter: 'blur(12px)',
  padding: '30px',
  borderRadius: '25px',
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'space-evenly',
  h2: {
    background: 'rgba(250, 250, 250, 0.9)',
    borderRadius: '10px',
    padding: '5px 10px',
    '@media (min-width: 601px) and (max-width: 1200px)': {
      fontSize: '1.5rem',
    },
    '@media (max-width: 600px)': {
      fontSize: '1.1rem',
    },
  },
  formContainer: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    gap: '30px',
  },
  successMessage: {
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.8rem',
  },
  inputsContainer: {
    height: '60%',
    width: '60%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  inputs: {
    marginBottom: '25px',
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    gap: '20px',
  },
  fields: {
    width: '100%',
  },
  para: {
    fontSize: '2.5rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    width: '35%',
    height: '60%',
  },
};
