export const styles = {
  width: '70vw',
  maxWidth: '1500px',
  '@media (max-width: 1200px)': {
    width: '95vw',
    height: 'auto',
    maxHeight: 'unset',
    margin: '80px 0 50px 0',
  },
  height: '85vh',
  maxHeight: '1000px',
  background: 'rgba(0, 0, 28, 0.8)',
  backdropFilter: 'blur(12px)',
  padding: '30px',
  borderRadius: '25px',
  display: 'flex',
  flexDirection: 'column',
  h2: {
    background: 'rgba(250, 250, 250, 0.9)',
    borderRadius: '10px',
    padding: '5px 10px',
    marginBottom: '20px',
    '@media (min-width: 601px) and (max-width: 1200px)': {
      fontSize: '1.5rem',
    },
    '@media (max-width: 600px)': {
      fontSize: '1.1rem',
    },
  },
  card: {
    width: '100%',
    height: '550px',
    background: 'transparent',
    display: 'flex',
  },
  cardMedia: {
    height: '85%',
    width: '60%',
    objectFit: 'contain',
  },
  chip: {
    background: 'rgba(250, 250, 250, 0.9)',
    fontWeight: 700,
    fontFamily: 'Oxygen',
    width: '100px',
  },
  content: {
    width: '40%',
    display: 'flex',
    flexDirection: 'column',
    gap: '25px',
    padding: '15px 30px',
  },
  paragraph: {
    fontSize: '1.1rem',
    display: 'flex',
    alignItems: 'center',
  },
  link: {
    textDecoration: 'none',
    fontSize: '0.8rem',
    width: '120px',
    textAlign: 'center',
    borderRadius: '10px',
    padding: '8px 10px',
    color: '#1495ff',
    letterSpacing: '1px',
    outline: '1px solid #1495ff',
    '&:hover': {
      background: '#0C2340',
      color: '#fff',
      outline: 'none',
    },
  },
  carousel: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
};
